// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p27
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:151

#ifndef _TAO_IDL_FOOC_OB8OBN_H_
#define _TAO_IDL_FOOC_OB8OBN_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "Foo_Export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO Foo_Export
// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:37

namespace Baz
{
  // TAO_IDL - Generated from
  // D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:260

  

  struct Bar;

  typedef
    ::TAO_Fixed_Var_T<
        Bar
      >
    Bar_var;

  typedef
    Bar &
    Bar_out;

  
  // TAO_IDL - Generated from
  // D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:50

  

  struct Foo_Export Bar
  {
    // TAO_IDL - Generated from
    // D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:304

    
    typedef Bar_var _var_type;
    typedef Bar_out _out_type;
    
    ::CORBA::Long x;
  };


// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:65


} // module Baz
// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:66



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:934

  

  template<>
  class Arg_Traits< ::Baz::Bar>
    : public
        Fixed_Size_Arg_Traits_T<
            ::Baz::Bar,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_traits.cpp:60



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:45


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

Foo_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Baz::Bar &);
Foo_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, Baz::Bar &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:1666

#if defined (__ACE_INLINE__)
#include "FooC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

