/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_FOOJC_H
#define IDL2JNI_GENERATED_FOOJC_H
#include "FooC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "Foo_Export.h"
/* Generated by D:\OpenDDS-3.23.1\bin\idl2jni running on input file Foo.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: Baz */



/* Begin STRUCT: Bar */

Foo_Export
void copyToCxx (JNIEnv *jni, Baz::Bar &target, jobject source);
Foo_Export
void copyToJava (JNIEnv *jni, jobject &target, const Baz::Bar &source, bool createNewObject = false);

/* End STRUCT: Bar */

/* End MODULE: Baz */
#endif /* IDL2JNI_GENERATED_FOOJC_H */
