#include "FooJC.h"
#include "idl2jni_runtime.h"

/* Generated by D:\OpenDDS-3.23.1\bin\idl2jni running on input file Foo.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: Baz */



/* Begin STRUCT: Bar */

void copyToCxx (JNIEnv *jni, Baz::Bar &target, jobject source)
{
  jclass clazz = jni->GetObjectClass (source);
  {
    jfieldID fid = jni->GetFieldID (clazz, "x", "I");
    target.x = jni->GetIntField (source, fid);
  }
  jni->DeleteLocalRef (clazz);
}

void copyToJava (JNIEnv *jni, jobject &target, const Baz::Bar &source, bool createNewObject)
{
  jclass clazz;
  if (createNewObject)
    {
      clazz = findClass (jni, "Baz/Bar");
      jmethodID ctor = jni->GetMethodID (clazz, "<init>", "()V");
      target = jni->NewObject (clazz, ctor);
    }
  else
    {
      clazz = jni->GetObjectClass (target);
    }
  {
    jfieldID fid = jni->GetFieldID (clazz, "x", "I");
    jni->SetIntField (target, fid, source.x);
  }
  jni->DeleteLocalRef (clazz);
}


/* End STRUCT: Bar */

/* End MODULE: Baz */
