// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p27
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\OpenDDS-3.23.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:648

#ifndef _TAO_IDL_FOOTYPESUPPORTS_LIOWCH_CPP_
#define _TAO_IDL_FOOTYPESUPPORTS_LIOWCH_CPP_


#include "FooTypeSupportS.h"

#endif /* ifndef */

